In [ ]:
# Pandas
# Pandas is a powerful and flexible Python package that allows you to work with labeled and
# time series data. It also provides statistics methods, enables plotting, and more.
# One crucial feature of pandas is its ability to write and read Excel, CSV, and many other types of files.

# Reading An Excel File
# Reading A CSV File
# Reading tab-delimited file
# Reading A JSON File
# Uploading Local Files In Google Colab


# https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx

# https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv

# https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt

# https://raw.githubusercontent.com/yash240990/Python/master/simple.json

In [ ]:
import pandas as pd

In [ ]:
# Reading An Excel File
# read_excel()

data = pd.read_excel('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
data

,id,first_name,last_name,email,gender,ip_address
0,1,Merle,Draisey,mdraisey0@squarespace.com,Bigender,20.70.199.51
1,2,Casey,Sheach,csheach1@deviantart.com,Male,226.126.229.167
2,3,Darya,Leivers,dleivers2@imgur.com,Female,247.209.88.235
3,4,Fancie,Casebourne,fcasebourne3@g.co,Female,172.34.162.239
4,5,Jenilee,Vsanelli,jvsanelli4@fc2.com,Female,200.104.246.2
...,...,...,...,...,...,...
995,996,Lutero,Yurov,lyurovrn@un.org,Male,95.146.16.187
996,997,Verla,Peery,vpeeryro@com.com,Female,172.90.253.234
997,998,Fran,Langran,flangranrp@ft.com,Male,123.179.99.154
998,999,Gabbi,Cummins,gcumminsrq@jugem.jp,Female,190.13.174.159
999,1000,Gloriane,Marc,gmarcrr@businessweek.com,Female,139.87.192.32

In [ ]:
# Reading The Data From A Different Sheet
# Load The Entire Excel Workbook

excelFile = pd.ExcelFile ('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelFile.sheet_names

['data', 'Sheet2']

In [ ]:
# Reading A CSV File
# Coma Seperated Value

data = pd.read_csv ('https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv')
data

NameError: name 'pd' is not defined

In [ ]:
# Reading tab-delimited file
# Reading the content of Excel File saved with .txt format

data = pd.read_csv('https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt' , sep='\t')
data

     SepalLength  SepalWidth  PetalLength  PetalWidth  Species Species Name
0             50          33           14           2        1       Setosa
1             64          28           56          22        3    Virginica
2             65          28           46          15        2   Versicolor
3             67          31           56          24        3    Virginica
4             63          28           51          15        3    Virginica
..           ...         ...          ...         ...      ...          ...
145           52          35           15           2        1       Setosa
146           58          28           51          24        3    Virginica
147           67          30           50          17        2   Versicolor
148           63          33           60          25        3    Virginica
149           53          37           15           2        1       Setosa

[150 rows x 6 columns]

In [ ]:
# Reading a JSON
data = pd.read_json('https://raw.githubusercontent.com/yash240990/Python/master/simple.json')
data

     id   name  math  physics  chemistry
0  A001    Tom    60       66         61
1  A002  James    89       76         51
2  A003  Jenny    79       90         78

In [ ]:
# Uploading Local Files In Google Collab

from google.colab import files      # file upload wizard
uploaded = files.upload ()

Saving sample.csv to sample.csv

In [ ]:
!ls  # List The Files

sample.csv  sample.csv.csv

In [ ]:
data = pd.read_csv('sample.csv')
data

,id,first_name,last_name,email,gender,ip_address
0,1,Latrena,Smales,lsmales0@mozilla.com,Genderfluid,29.127.175.174
1,2,Sal,Ferriere,sferriere1@addthis.com,Male,57.76.159.203
2,3,Kippar,Sharratt,ksharratt2@foxnews.com,Male,115.111.9.79
3,4,Barnett,Lackinton,blackinton3@flavors.me,Male,160.10.205.41
4,5,Ashlee,Farnon,afarnon4@engadget.com,Female,35.237.63.199
...,...,...,...,...,...,...
995,996,Niki,Luter,nluterrn@1und1.de,Female,120.19.221.6
996,997,Sal,Grafham,sgrafhamro@feedburner.com,Male,50.36.14.64
997,998,Maddy,Donneely,mdonneelyrp@ed.gov,Female,108.201.133.210
998,999,Bernie,McFade,bmcfaderq@wsj.com,Male,54.164.57.62
999,1000,Fannie,Lapsley,flapsleyrr@scientificamerican.com,Female,246.243.91.14